### ISSUE TITLE
CHIRP Snap build is missing access to the Stock Config files.

### ISSUE THREAD

**Issue by KC9HI** [goldstar611/chirp#1]
Is there reason that the Snap build of CHRIP is missing support for the Stock Config files. All other builds (Windows, Linux, macOS and Flatpak) still have it.

Jim KC9HI

**Comment by goldstar611** [comment]
Hey Jim,

Thanks for following up on the redmine ticket. I just verified that the snap version is indeed missing the stock config files. There's probably a single line fix for this that maps the input stock_config dir to ~/.chirp/stock_config.
