### ISSUE TITLE
CHIRP Stops

### ISSUE THREAD

**Issue by tpalmatier** [goldstar611/chirp#2]
The new CHIRP next-build comes up on the screen for a split second and then stops.

**Comment by goldstar611** [comment]
Hey Terry,
Thanks for the bug report. This is my fault attempting to package up chirp-next incorrectly.

Until I get it working correctly I will set the snap version back to the last working python 2 version. If you uninstall and re install it should fix it. Don't forget to re add the serial port permission after the re install.
Let me know if that helps

**Comment by tpalmatier** [comment]
Thanks Tony, that worked out fine.  Looking forward to the new version.


Terry
AC8NR
________________________________
